### PR TITLE
Feat/use full page width

### PR DESCRIPTION
**Pull request by mmehmetAliIzci**
# Changes

## Related issues

https://github.com/FrontMen/fm-hours/issues/58

## Removed

Remove superflous `page-wrapper` div from necessary pages

## Changed

`content-wrapper` now has max-widht. All the pages are tested and looking relatively fine. 

## How to test

Go through all the pages and see if there is something that is not looking too pretty

### CODE REVIEW

**Review by vladPinteaFrontmen — APPROVED** [review]
Looks good, but I wonder if it wouldn't be possible to move all this wrapper area of code to a parent, ot to a "layout", since all pages seems to share the wrapper. Otherwise, works as intended

**Comment by mmehmetAliIzci** [comment]
https://user-images.githubusercontent.com/7356299/125445197-f21f878a-3c7c-4b0a-bb7c-98386f7abf97.mov

After rebase. Dont forget to make the screen smaller to test

**Comment by mmehmetAliIzci** [comment]
@vladPinteaFrontmen Not sure if we wanna do this because `layout-wrapper` is including topbar and admin sidebar

**Review by vladPinteaFrontmen — COMMENTED** [review]
customers/:id, does not seem to conform to the full-width layout 
image

**Comment by mmehmetAliIzci** [comment]
I made the `customer/:id` not full screen because how ugly it looked with 2 screenwide textinputs with 3 buttons which has the same uglyness by being on the end corner of the screen 🤷

**Pull request merged**
