### PR TITLE
feat: show theoratical hours in the total row

### PR DESCRIPTION
**Pull request by mmehmetAliIzci**
# Changes

## Related issues

https://github.com/FrontMen/fm-hours/issues/196

## Added

Added new "theoratical hours" information to `weekly-timesheet-row`

## How to test

See if there theoratical hours are present 🤷‍♂️ 

## Screenshots

image

### CODE REVIEW

**Comment by italoteix** [comment]
The code looks fine, but I think that `workHours` suits it better for regular hours and `absenceHours` for the leave table.

For reference, this is what we get from the work-scheme api:
- date:
    - string 
    - ‘YYYY-MM-DD’
- absence_hours: 
    - number
    - Leave hours
- holiday
    - number
    - 1 if public holiday, 0 if not
- present_hours
    - number
    - Defaults to the same value as work_hours
    - Doesn't have a use case for Frontmen
- theoretical_hours:
    - number
    - Work hours by contract
- work_hours:
    - number
    - Theoretical hours minus the leave (absence) hours

**Comment by mmehmetAliIzci** [comment]
After @sanderdejong88 and @lassecapel suggestions:
image

**Comment by mmehmetAliIzci** [comment]
> The code looks fine, but I think that `workHours` suits it better for regular hours and `absenceHours` for the leave table.
> 
> For reference, this is what we get from the work-scheme api:
> 
> * date:
>   
>   * string
>   * ‘YYYY-MM-DD’
> * absence_hours:
>   
>   * number
>   * Leave hours
> * holiday
>   
>   * number
>   * `1` if public holiday, `0` if not
> * present_hours
>   
>   * number
>   * Usually the same value as work_hours
>   * Doesn't have a use case for Frontmen
> * theoretical_hours:
>   
>   * number
>   * Work hours by contract
> * work_hours:
>   
>   * number
>   * Theoretical hours minus the leave (absence) hours

We wont be showing total for leave table. But otherwise i will use `workHours`. Good catch 👍

**Comment by lassecapel** [comment]
i think in case of non working days it should be 0/0 or just a 0. "0/" looks a bit odd to me

**Comment by sanderdejong88** [comment]
@mmehmetAliIzci what does it look like on vacation days/holidays etc.? Maybe on days we don't "expect" hours like weekends and those days we can just show a dash?

**Comment by mmehmetAliIzci** [comment]
Showing a dash instead of `0/` now:

image

**Review by italoteix — APPROVED** [review]

**Pull request merged**
